### ISSUE TITLE
Error when project inited.

### ISSUE THREAD

**Issue by MarcGraham** [UniBO-PRISMLab/wam#18]
Hi, 

System: 
macOS Big Sur
node 15.10.0
npm 7.10.1
nvm 0.37.2

I was giving WAM a try and got this error when trying to init a project:

`xxxx@xxxx wot % wam init ./wotTutorialThermostat
 __        ___    __  __ 
 \ \      / / \  |  \/  |
  \ \ /\ / / _ \ | |\/| |
   \ V  V / ___ \| |  | |
    \_/\_/_/   \_\_|  |_|
                         
? language: JavaScript
? name: wotTutorialThermostat
? version: 1.0.0
? description: 
? Enter the keywords separated by a comma: 
? author: 
? license: Apache License 2.0

Thanks!; installing packages using npm:
/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/npm/lib/npm.js:163
      throw new TypeError('callback must be a function if provided')
            ^

TypeError: callback must be a function if provided
    at Object.load (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/npm/lib/npm.js:163:13)
    at /Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/utils/npm-install.js:9:30
    at new Promise (<anonymous>)
    at Object.install [as default] (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/utils/npm-install.js:8:12)
    at Command.<anonymous> (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/commands/init.js:86:53)
    at step (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/commands/init.js:33:23)
    at Object.next (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/commands/init.js:14:53)
    at fulfilled (/Users/marc/.nvm/versions/node/v15.10.0/lib/node_modules/@arces-wot/wam/dist/src/commands/init.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

I went ahead and ran npm install in the project directory and completed the tutorial -- it seems to work correctly.

**Comment by relu91** [comment]
Thank you so much for using `wam` and reporting here. That's probably because npm does not have a real stable API. I'll look into it. Maybe it's time to implement some CI tests 🤔 .

**Comment by relu91** [comment]
should be fixed now, please re-open if not!

**Comment by MarcGraham** [comment]
Works for me! Thanks.
